options:
  email:
    type: string
    description: Account email address
  server:
    type: string
    description: Certificate authority server
    default: "https://acme-v02.api.letsencrypt.org/directory"
  aws_access_key_id:
    type: string
    default: ""
    description: AWS Access Key ID
  aws_secret_access_key:
    type: string
    default: ""
    description: AWS Secret Access Key
  aws_region:
    type: string
    description: AWS Region
  aws_shared_credentials_file:
    type: string
    default: ""
    description: Path to the file that contains the AWS credentials
  aws_hosted_zone_id:
    type: string
    description: AWS Hosted Zone ID
  aws_max_retries:
    type: string
    default: "5"
    description: The number of maximum returns the service will use to make an individual API request
  aws_polling_interval:
    type: string
    default: "15"
    description: Time between DNS propagation checks in seconds
  aws_propagation_timeout:
    type: string
    default: "3600"
    description: Maximum waiting time for DNS propagation in seconds
  aws_ttl:
    type: string
    default: "120"
    description: The TTL of the TXT record used for the DNS challenge
